### ISSUE TITLE
Consumer skips messages

### ISSUE THREAD

**Issue by themoritz** [kim/data-ringbuffer#3]
When I run the following code, the consumer randomly skips messages (so the resulting list is only a subset of [0..99].

    import           Control.Concurrent
    import           Control.Monad
    import           Data.IORef
    import           Data.RingBuffer
    import           Data.RingBuffer.Vector

    bufSize,modMask,iters :: Int
    bufSize = 2 ^ (10 :: Int)
    modMask = bufSize - 1
    iters = 100

    main :: IO ()
    main = do
        listlog <- newIORef []
        logger <- newConsumer $ \i -> modifyIORef listlog (i:)
        seqr <- newSequencer [logger]
        let barrier = newBarrier seqr []
        buffer <- newRingBuffer bufSize 0
        done <- newEmptyMVar

        forkIO $ mapM_ (\i -> publishTo buffer modMask seqr i i) [0..iters]
        forkIO $ consume buffer barrier logger done

        void $ takeMVar done
        list <- readIORef listlog
        print list
      where
        consume buf bar cons lock = do
          consumeFrom buf modMask bar cons
          consumed <- consumerSeq cons
          if consumed == iters
            then putMVar lock ()
            else consume buf bar cons lock

Is there a bug or did I do something wrong? Interestingly, when the consumer prints every message, it doesn't skip any of them.

**Comment by kim** [comment]
Looks like the classic: off-by-one error. Will fix.

**Comment by themoritz** [comment]
You are right, already found it:

https://github.com/themoritz/data-ringbuffer/commit/d8809df4640cb57293f820cbdcaf64cc8df1ad95

**Comment by kim** [comment]
Thanks.

I noticed you're making other changes, too. Should I wait for a PR?

**Comment by themoritz** [comment]
Indeed, I have already fixed a second bug and migrated to the atomic-primops package.

The next thing I plan to do is to introduce consumer annotations. Did you already have ideas on how to add that feature?

So yes, I will probably make a PR soon.

**Comment by kim** [comment]
> [...] introduce consumer annotations

I don't know what that is. Any pointers?

> So yes, I will probably make a PR soon.

Awesome

**Comment by themoritz** [comment]
Regarding annotations: see http://trishagee.github.io/post/dissecting_the_disruptor_wiring_up_the_dependencies/ (section "modifying entries")

**Comment by kim** [comment]
IIUC, this is about arbitrarily-shaped mutable entries in the ring buffer, which only get allocated once (when the ring buffer is created), ie.:

```haskell
newtype RingBuffer a = RingBuffer (Vector a)
```

The interface would need to change, as publishers need to provide an update function for `a`. This would be closer to the (current) Java implementation.

I'd be curious about the performance characteristics, especially regarding the different options of how to implement mutability of `a` (eg. wrap the whole `a` in  an`IORef` vs. `a` being a record with mutable field(s)).

**Comment by themoritz** [comment]
My first idea was to have multiple ring buffers:

https://github.com/themoritz/data-ringbuffer/tree/transform

It's working quite well (also performance seems to be ok) but the disadvantage is that it's prone to user errors right now.

**Comment by kim** [comment]
You may overwrite values in the destination vector before any consumers see them, as you're not coordinating access to the second vector. Also, the example in the article, where a consumer `C3` is dependent on two concurrent consumers `C1` and `C2` modifying the entries, could not be implemented (unless `C1` and `C2` operate sequentially).

As an alternative to my previous proposal, one could also allow an 'in-place' update on the mutable vector.

**Comment by kim** [comment]
@themoritz if you don't mind, I'd close this ticket and continue the discussion on #4
